services:
  - type: web
    name: url-shortener
    env: node
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: HOST
        value: 0.0.0.0
